from pydantic import BaseModel

# This module defines the output schema for the RCA response generated by the LLM.
class RCAResponse(BaseModel):
    root_cause:str
    confidence:float
    recommended_action:str