"""
Autonomous AI Incident Resolution Platform
----------------------------------------------

Run:

streamlit run src/demo/demo_app.py
"""

import streamlit as st

# --------------------------------------------------------
# Page Configuration
# --------------------------------------------------------

st.set_page_config(
    page_title="Autonomous AI Incident Resolution Platform",
    page_icon="🤖",
    layout="wide",
    initial_sidebar_state="expanded"
)

# --------------------------------------------------------
# Custom CSS
# --------------------------------------------------------

st.markdown("""
<style>

.main-header{
    font-size:36px;
    font-weight:bold;
    color:#0E76A8;
}

.sub-header{
    font-size:18px;
    color:#808080;
}

.metric-card{
    background:#f6f8fa;
    padding:15px;
    border-radius:10px;
    border:1px solid #ddd;
}

.stage{
    border-left:6px solid #0E76A8;
    padding-left:10px;
    margin-bottom:12px;
}

</style>
""", unsafe_allow_html=True)

# --------------------------------------------------------
# Header
# --------------------------------------------------------

st.markdown(
    '<p class="main-header">🤖 Autonomous AI SRE Incident Resolution Platform</p>',
    unsafe_allow_html=True
)

st.markdown(
    '<p class="sub-header">PPO + RAG + LLM for Autonomous Production Incident Resolution</p>',
    unsafe_allow_html=True
)

st.divider()

# --------------------------------------------------------
# Sidebar
# --------------------------------------------------------

st.sidebar.title("⚙ Demo Configuration")

environment = st.sidebar.selectbox(
    "Environment",
    [
        "Kubernetes Cluster",
        "Virtual Machines",
        "AWS EC2",
        "Azure AKS",
        "Payment Platform",
        "Banking Application",
        "E-Commerce"
    ]
)

incident = st.sidebar.radio(
    "Incident Type",
    [
        "Memory Leak",
        "CPU Spike",
        "HTTP 500 Errors",
        "Database Latency",
        "Disk Full",
        "Network Packet Loss"
    ]
)

severity = st.sidebar.select_slider(
    "Severity",
    options=[
        "Low",
        "Medium",
        "High",
        "Critical"
    ],
    value="High"
)

st.sidebar.divider()

random_incident = st.sidebar.checkbox(
    "🎲 Random Production Incident"
)

generate = st.sidebar.button(
    "▶ Generate Incident",
    use_container_width=True
)

# --------------------------------------------------------
# Layout
# --------------------------------------------------------

left, right = st.columns([1.1,1.2])

# ========================================================
# LEFT SIDE
# ========================================================

with left:
    st.subheader("🚨 Incident Summary")
    summary = st.container(border=True)

    with summary:
        st.info("Click **Generate Incident** to begin the autonomous resolution workflow.")

    st.subheader("📈 Live Telemetry")
    telemetry = st.container(border=True)

    with telemetry:
        c1,c2,c3 = st.columns(3)

        c1.metric("CPU","--")
        c2.metric("Memory","--")
        c3.metric("Latency","--")

        c4,c5,c6 = st.columns(3)

        c4.metric("HTTP 5xx","--")
        c5.metric("DB Latency","--")
        c6.metric("Pods","--")

# ========================================================
# RIGHT SIDE
# ========================================================

with right:
    st.subheader("🧠 Autonomous Resolution Workflow")
    workflow = [

        ("1️⃣ Telemetry Collection",
         "Waiting..."),

        ("2️⃣ State Builder",
         "Waiting..."),

        ("3️⃣ RAG Knowledge Retrieval",
         "Waiting..."),

        ("4️⃣ Root Cause Analysis",
         "Waiting..."),

        ("5️⃣ PPO Decision Engine",
         "Waiting..."),

        ("6️⃣ Execute Action",
         "Waiting..."),

        ("7️⃣ Reward Evaluation",
         "Waiting..."),

        ("8️⃣ Incident Resolution",
         "Waiting...")
    ]

    placeholders = {}

    for title,status in workflow:
        with st.container(border=True):
            st.markdown(f"### {title}")
            placeholders[title] = st.empty()
            placeholders[title].info(status)

# --------------------------------------------------------
# Bottom Tabs
# --------------------------------------------------------

st.divider()

tab1,tab2,tab3,tab4 = st.tabs(
    [
        "📚 Retrieved Incidents",
        "🎯 PPO Policy",
        "🏆 Reward",
        "📜 Execution Logs"
    ]
)

with tab1:
    st.info("Retrieved historical incidents will appear here.")

with tab2:
    st.info("Action probabilities generated by PPO will appear here.")

with tab3:
    st.info("Structured Reward + LLM Reward + Adaptive Alpha")

with tab4:
    st.info("Execution timeline will appear here.")

# --------------------------------------------------------
# Footer
# --------------------------------------------------------

st.divider()
st.caption("Autonomous AI SRE Platform • PPO + RAG + LLM • M.Tech Dissertation Demo")

# --------------------------------------------------------
# Placeholder for next phase
# --------------------------------------------------------

if generate:
    st.success(f"Generating {incident} incident in {environment} ({severity})...")
    st.info("Phase 2 will connect the Incident Generator and Telemetry Engine.")